version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: meu_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: meu_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:

